services:
  cache-server:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:7.0.0
    platform: linux/amd64
    ports:
      - '3000:3000'
    environment:
      DEBUG: 1
    env_file:
      - .docker_env_cache
    volumes:
      - cache-data:/app/.data
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null","http://localhost:3000" ]
      start_period: 10s
      start_interval: 1s
  runner:
    build:
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file:
      - .docker_env_runner
    privileged: true
    links:
      - cache-server
    stop_grace_period: 30s
    environment:
      RUNNER_REPO: saez0pub/testing-self-hosted-cache
      RUNNER_GRACEFUL_STOP_TIMEOUT: 10
      RUNNER_NAME: runner-test-compose
      RUNNER_LABELS: self-hosted-test
    depends_on:
      cache-server:
        condition: service_healthy

volumes:
  cache-data:

networks:
  default: