services:
  cache-server:
    image: ghcr.io/falcondev-oss/github-actions-cache-server:dev
    platform: linux/amd64
    ports:
      - '3000:3000'
      - '8000:8000'
    environment:
      API_BASE_URL: http://localhost:3000
      CA_KEY_PATH: /run/secrets/ca_key
      CA_CERT_PATH: /run/secrets/ca_cert
      NITRO_CLUSTER_WORKERS: ''
    volumes:
      - cache-data:/app/.data
    secrets:
      - ca_key
      - ca_cert
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null","http://localhost:3000" ]
      start_period: 10s
      start_interval: 1s
  runner:
    build:
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file:
      - .docker_env
    privileged: true
    links:
      - cache-server
    environment:
      RUNNER_REPO: saez0pub/testing-self-hosted-cache
      RUNNER_GRACEFUL_STOP_TIMEOUT: 10
      RUNNER_NAME: runner-test-compose
      RUNNER_LABELS: self-hosted-test
      CACHE_CA_CERT_PATH: /run/secrets/ca_cert
    depends_on:
      cache-server:
        condition: service_healthy
    secrets:
      - ca_cert

volumes:
  cache-data:

secrets:
  ca_key:
    file: ./key.pem
  ca_cert:
    file: ./cert.pem

networks:
  default: